/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import controller.ClientController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Message;
import model.User;

/**
 *
 * @author Admin
 */
public class UserOnlineView extends javax.swing.JFrame {

    /**
     * Creates new form UserOnlineView
     */
    
    
     static  ArrayList<User> listOnline;
     static ArrayList<User> listUserOnline = new ArrayList<>();
     static ArrayList<User> listRanking = new ArrayList<>();
     DefaultTableModel tableModel ;
     static  UserOnlineView userOnlineView;
    public UserOnlineView() {
      Message userMessage = new Message(null, Message.Label.LIST_USERS);
      LoginView.clientController.sendData(userMessage);
      Message listMessage = (Message) LoginView.clientController.receiveData();
      listUserOnline = (ArrayList<User>) listMessage.getObject();
       initComponents();

        tableModel = (DefaultTableModel) tblUserOnline.getModel();
       
        tableModel.setRowCount(0);
         for(User i : listUserOnline){
            tableModel.addRow(i.toObject());
        }
         
       
  
    }
     public int showConfirmDialog(String content) {
        return JOptionPane.showConfirmDialog(userOnlineView, content);
    }
     public void showMessage(String content) {
        JOptionPane.showMessageDialog(userOnlineView, content);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserOnline = new javax.swing.JTable();
        UserOnline_btnInvite = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        UserOnline_btnRanking = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tblUserOnline.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "User Name", "FullName", "Point", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUserOnline);

        UserOnline_btnInvite.setText("Invite");
        UserOnline_btnInvite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserOnline_btnInviteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("MATCH PHOTO GAME ");

        UserOnline_btnRanking.setText("Ranking");
        UserOnline_btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserOnline_btnRankingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(UserOnline_btnInvite, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(UserOnline_btnRanking))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserOnline_btnInvite)
                    .addComponent(UserOnline_btnRanking))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserOnline_btnInviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserOnline_btnInviteActionPerformed
        // TODO add your handling code here:
        int row = tblUserOnline.getSelectedRow();
       int id = (int) tblUserOnline.getValueAt(row, 0);
        String name = tblUserOnline.getValueAt(row, 2).toString();
        int point = (int) tblUserOnline.getValueAt(row, 3);
        System.out.println("name selected " + name + " " + "point" + point);
        User user = new User(id, name, point);
        for (User acc : listUserOnline) {
            if (acc.getName().equals(name) && acc.getPoint() == point) {
               user = acc;
                
            }
        }
        Message message = new Message(user, Message.Label.CHALLENGE);
        LoginView.clientController.sendData(message);
        System.out.println("Da gui yeu cau invite toi "+ user.getName());
       
    }//GEN-LAST:event_UserOnline_btnInviteActionPerformed

    private void UserOnline_btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserOnline_btnRankingActionPerformed
        // TODO add your handling code here:
        Message messageSendRank = new Message(null, Message.Label.GET_SCOREBOARD);
        LoginView.clientController.sendData(messageSendRank);
        System.out.println("Da gui yeu cau Ranking");
        Message messageReceiRanking = (Message) LoginView.clientController.receiveData();
        System.out.println("Da nhan ranking view");
      
        listRanking = (ArrayList<User>)messageReceiRanking.getObject();
         if(messageReceiRanking.getLabel().toString()== "REPLY_SCOREBOARD"){
            RankingView rankingView = new RankingView();
            rankingView.setVisible(true);
         }
         else{
             System.out.println("Ranking view fail");
         }
    }//GEN-LAST:event_UserOnline_btnRankingActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Message message = new Message(null, Message.Label.LOGOUT);
        LoginView.clientController.sendData(message);
        Message messageLog = (Message) LoginView.clientController.receiveData();
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserOnlineView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserOnlineView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserOnlineView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserOnlineView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserOnlineView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UserOnline_btnInvite;
    private javax.swing.JButton UserOnline_btnRanking;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUserOnline;
    // End of variables declaration//GEN-END:variables
}
